### ISSUE TITLE
Caching doesn't work with properties

### ISSUE THREAD

**Issue by sallyruthstruik** [sh4nks/flask-caching#10]
Hello!

I faced with such problem:

I tried to memoize property getter in this way:
```
class TestClass:

            def __init__(self, value):
                self._value = value

            @property
            @cache.memoize(100)
            def value(self):
                return self._value
```
and I got:
`
DeprecationWarning("Deleting messages by relative name is "
                                     "no longer reliable, please switch to a "
                                     "function reference.")
`

I thing it is bug, and I fix it in this pull request: https://github.com/sh4nks/flask-caching/pull/9

**Comment by sh4nks** [comment]
See my reply in #9.
