### ISSUE TITLE
Leftover files in pypi package (1.7.0) cause import name conflict in UWSGICache (Python 2.7)

### ISSUE THREAD

**Issue by pogliamarci** [sh4nks/flask-caching#102]
Hello,

I installed the latest release from PyPi, and I got the same issue with UWSGICache and Python2.7 that was solved by #100 .

Digging a little bit in the `.whl` file, I noticed that it contains both `uwsgi.py` and `uwsgicache.py`, basically rendering #100 useless (as the file with the old name gets installed, and it gets imported). Instead, in the `.tar.gz` file instead there is only the updated `uwsgicache.py` file.

The solution would be to regenerating the distribution file `Flask_Caching-1.7.0-py2.py3-none-any.whl` in PyPi without the old `uwsgi.py`.

Thanks a lot,
--Marcello

**Comment by sh4nks** [comment]
Thanks for the report. I'll push a new release to PyPI shortly.

**Comment by sh4nks** [comment]
I published a new release without the leftover files.
