### ISSUE TITLE
Use pallets/cachelib for backends

### ISSUE THREAD

**Issue by dchevell** [sh4nks/flask-caching#103]
In #72 we learned werkzeug was removing `werkzeug.contrib.cache`, and in #75 we moved the code for that dependency directly into Flask-Caching.

It turns out `werkzeug.contrib.cache` was never shuttered, it just got moved into its own project: pallets/cache

We should undo the work in #75 and move back to depending on the external library, which is likely going to receive more attention and maintenance than we could give it here

**Comment by sh4nks** [comment]
We probably would have to find a different workaround for https://github.com/sh4nks/flask-caching/pull/94.

**Comment by gergelypolonkai** [comment]
Indeed, but it also removes a lot of maintenance burden introduced with #75.

Maybe pallets/werkzeug#1268 should be re-reported in pallets/cache?

**Comment by neilsh** [comment]
link to the actual project: https://github.com/pallets/cachelib
