### ISSUE TITLE
Is there a way to NOT cache when retuning None or another arbitrary value?

### ISSUE THREAD

**Issue by aardvark82** [sh4nks/flask-caching#105]
Hi there,
is there a way to specify that Flask-Caching does not cache None results? This would help for e.g. when lazy loading objects, etc... 

I find it difficult to invalidate the cache (struggling w params, etc...) and figured there might be a way to define that methods returning None are not cached (until they return a valid response)

**Comment by gergelypolonkai** [comment]
If you are using the `cached` decorator, you can use the `response_filter` parameter. It must be a callable that gets the response of the cached function and returns a boolean; if the returned value is `False`, the response is not cached.

**Comment by aardvark82** [comment]
Thanks for the tip 
- I'm using memoize(), is there something similar for that?
- Or what is a way to use .cached() instead of memoize for non-view functions?

**Comment by gergelypolonkai** [comment]
`memoize` doesn’t support this mechanism as of now. However, neither `cached` nor `memoize` make a difference between not finding a key in a cache and getting an actual `None` value from the cache.

This means if you cache a `None` value for any reason, your function will run again (which i consider a bug, but let’s discuss it elsewhere), thus resulting in the behaviour you want.

**Comment by aardvark82** [comment]
Good to know, thank you!
