### ISSUE TITLE
Any breaking changes between Flask-Caching and Flask-Cache?

### ISSUE THREAD

**Issue by neilsh** [sh4nks/flask-caching#11]
Are there any breaking changes between Flask-Caching 1.0.1 and the last version of Flask-Cache (0.13)? Other than having to change `from flask.ext.cache import Cache` to `from flask_caching import Cache`, of course. Looking through the changelog I don't see anything that looks like a breaking change, but wanted to verify. Perhaps it would be worthwhile to mention in the README.md?

**Comment by sh4nks** [comment]
Not that I know of. I have been using Flask-Cache for FlaskBB and after I forked it I have just changed the imports from `flask_cache` to `flask_caching` and it still works without problems.
