### ISSUE TITLE
run fsck on the repo

### ISSUE THREAD

**Issue by ageis** [sh4nks/flask-caching#110]
While pulling your repository, I got this result:

```error: object 2898a46f3502ed61aa4a154b63f21d6c1a19d15d: zeroPaddedFilemode: contains zero-padded file modes
fatal: fsck error in packed object
fatal: index-pack failed
```

This is because I have the following set in my gitconfig:
```
[receive]
        fsckObjects = true
[transfer]
        fsckObjects = true
[fetch]
        fsckObjects = true
```

built-in git fsck should fix it, but [git-repair](https://git-repair.branchable.com/) is a more heavy duty tool if that doesn't take care of the issue. also you'll likely be rewriting the history and having to force push so depending on how far back this object is in time, you may want to think about the consequences and possibly could be stuck with it.

**Comment by gergelypolonkai** [comment]
Where did you pull from? Was it GitHub? If so, i don’t think they provide a way to run `git-fsck` on their own internal repos.

**Comment by ageis** [comment]
Yes, GitHub. No, but that's what I said -- you can do it locally and then rebase/force push, which will have consequences for people downstream of you.

**Comment by sh4nks** [comment]
As a fix for this would be too intrusive, I'll not fix this. You can ignore this by disabling the fsck check while cloning this repository:
```
git clone --config transfer.fsckobjects=false \
    --config receive.fsckobjects=false \
    --config fetch.fsckobjects=false \
    https://github.com/sh4nks/flask-caching.git
```
