### ISSUE TITLE
how ignore some jinjia Snippets?

### ISSUE THREAD

**Issue by Double1996** [sh4nks/flask-caching#114]
1.  I  cache my dashboard html by 
`@cache.cached(query_string=True, timeout=60 * 60, forced_update=True)
def dashboard()`

2. I want ignore  some html Snippets such like sidebar or nav 

3. what can I do ?

**Comment by gergelypolonkai** [comment]
If you cache a HTML response, you cache the whole response. If some parts of that HTML should not be cached, then you can’t cache the whole response.

In Jinja templates, though, you can cache some parts of the HTML with using a `{% cache %}` block:

```
{% cache 60 * 60 "cache_key" %}
This part is cached.
{% endcache %}
```

(Although, in my opinion, caching static text is not necessarily a good thing, but i hope you get the idea.)

This way, reversing your logic, you can cache most of your template but don’t cache others.

However, if your template is fast but the view itself has slow parts, you may want to refactor the view and cache the slow functions instead.

**Comment by Double1996** [comment]
I  use unless to solve my question
