### ISSUE TITLE
clear support passing in pattern

### ISSUE THREAD

**Issue by meeech** [sh4nks/flask-caching#125]
Any interest in a PR to allow for redis/memcache backend clear to support passing in optional prefix param?
Right now, its hard coded to KEY_PREFIX* but there's a scenario where it would be handy to have KEY_PREFIX_UUID_* (for example) where UUID is passed in
Any interest in a PR to support that use case, or a new method which supports that?

something like so should be backwards compat: 

```python
def clear(self, prefix=''):
        status = False
        if self.key_prefix:
            keys = self._read_clients.keys(self.key_prefix + prefix + "*")
            if keys:
                status = self._write_client.delete(*keys)
        else:
            status = self._write_client.flushdb()
        return status
```

**Comment by gergelypolonkai** [comment]
That sounds nice, but iʼm not a big fan of adding it exclusively to a few select backends. We'll, unless it canʼt be done for a backend, obviously.

**Comment by meeech** [comment]
fair enough. I thought it fit with redis/memcache since we have CACHE_KEY_PREFIX I'll have a look at the others.

**Comment by sh4nks** [comment]
Feel free to reopen it if you are still interested in implementing it.

**Comment by meeech** [comment]
@sh4nks cool thanks! Will do - i put caching on the back burner for now (i was busy exploring it) but i know it will come up again.

**Comment by mukeshsharma1201** [comment]
Meanwhile, other workarounds can be found here: https://stackoverflow.com/a/63476070/5022624
