### ISSUE TITLE
Redis not working

### ISSUE THREAD

**Issue by jkgeyti** [sh4nks/flask-caching#13]
I get some odd behaviour when trying to use Redis. Take the following example:

```
from flask import Flask
from flask_caching import Cache
import time

app = Flask(__name__)
app.config['CACHE_TYPE'] = 'RedisCache'
app.config['CACHE_REDIS_HOST'] = 'localhost'
app.config['CACHE_REDIS_PORT'] = '6379'

cache = Cache()
cache.init_app(app)

@app.route("/")
@cache.cached(timeout=5)
def index():
    return str(time.time())

app.run()
```

Accessing `/` throws:

```
Traceback (most recent call last):
  File "/Users/jensgeyti/git/data-web/env/lib/python3.5/site-packages/flask_caching/__init__.py", line 340, in decorated_function
    rv = self.cache.get(cache_key)
  File "/Users/jensgeyti/git/data-web/env/lib/python3.5/site-packages/werkzeug/contrib/cache.py", line 598, in get
    return self.load_object(self._client.get(self.key_prefix + key))
AttributeError: 'Flask' object has no attribute 'get'
```

It seems `Cache._set_cache` calls `cache_obj(app, config, cache_args, cache_options)`, but `cache_obj` is an instance of `wekzeug.contrib.cache.RedisCache` expecting arguments `(self, host='localhost', port=6379, password=None, db=0, default_timeout=300, key_prefix=None, **kwargs)`.

In essence, it seems Flask-Caching passes an `app` where it should pass a hostname. Any idea why that's happening?

The simple cache works fine.

**Comment by sh4nks** [comment]
It looks like it is using ``RedisCache`` from werkzeug directly instead of the 'wrapper' around RedisCache. Have you tried setting ``app.config['CACHE_TYPE']`` to ``redis``?

**Comment by jkgeyti** [comment]
It was due to the package `redis` not being installed. 

I don't know where I got the idea of using `RedisCache` directly from, but flask-caching could probably throw a better error than simply swallowing the ImportError in `backends.py`. I'm also not sure `RedisCache` should be exposed at all from the module?

```
# RedisCache is supported since Werkzeug 0.7.
try:
    from werkzeug.contrib.cache import RedisCache 
    from redis import from_url as redis_from_url
except ImportError:
    pass 
else:
    def redis(app, config, args, kwargs):
        ...
        return RedisCache(*args, **kwargs)
```

**Comment by sh4nks** [comment]
Yeah I think it shouldn't be exposed. If you want you can open a new PR for this. Otherwise I'll try to find some time this evening :)

**Comment by jkgeyti** [comment]
The suggested modification imports redis and RedisCache at the time of calling `redis()`, instead of at import time. I don't know if that causes any problems?

**Comment by jkgeyti** [comment]
https://github.com/sh4nks/flask-caching/pull/14
