### ISSUE TITLE
Setting TESTING=True doesn't disable cache

### ISSUE THREAD

**Issue by ajnisbet1c** [sh4nks/flask-caching#130]
The docs say 

> In addition the standard Flask TESTING configuration option is used. If this is True then Flask-Caching will use NullCache only.

but this isn't the case, the functionality was removed in flask-cache in https://github.com/thadeusb/flask-cache/commit/9988abf55204e6c08459c9e9dde785743ceef7ee as noted in https://github.com/thadeusb/flask-cache/issues/100

Either this reference should be removed, or the functionality should be added.

**Comment by vermaat** [comment]
I can verify this.
