### ISSUE TITLE
Decode_Responses = True

### ISSUE THREAD

**Issue by wbhst83** [sh4nks/flask-caching#132]
When using cache type of Redis, there are cases where I'm getting back bytes instead of strings for cache_key and thus throwing exceptions in third-party logging packages. I correct the issue by going to another type and therefore limited to Redis. I can also correct by monkey patching the third-parties package to check if the key is in bytes and then decode. I found that in Redis, you can ask Redis always to decode responses. I attempted to pass into flask-caching with an error. 

Code:
`cache = Cache(config={'CACHE_TYPE': 'redis',
                      'CACHE_OPTIONS': {'decode_responses': True}
                      })`

Error:
`File "/Users/XXXX/.virtualenvs/XXXX/lib/python3.7/site-packages/flask_caching/backends/rediscache.py", line 52, in __init__
"decode_responses is not supported by " "RedisCache."`

This is my first issue post, so forgive me if I left something out that should have been included.

**Comment by sh4nks** [comment]
This is not supported by Flask-Caching: https://github.com/sh4nks/flask-caching/blob/master/flask_caching/backends/rediscache.py#L60

Feel free to open a PR with the required changes to make it work or implement your own caching backend which supports it.
