### ISSUE TITLE
CACHE_TYPE="filesystem" 

### ISSUE THREAD

**Issue by sottom** [sh4nks/flask-caching#133]
__init__.py sets a default of `None` for `CACHE_DIR`, but it won't accept that default if `CACHE_TYPE="filesystem"`. It works when `CACHE_TYPE="simple"` though.

Maybe a default should be added so the code doesn't break when CACHE_DIR=None and CACHE_TYPE="filesystem".

**Comment by gergelypolonkai** [comment]
I don’t think there’s a default value that could be added here. What works for me on Linux might not be OK for another user on a Mac, and will definitely not work with my fellow dev on Windows. Instead, i’d add a warning, or even an exception if `filesystem` is used without `CACHE_DIR` set. How would that fit your workflow?

**Comment by sottom** [comment]
That makes sense. Yes, either of those options would work fine. Thank you!

**Comment by sh4nks** [comment]
Fixed with 806518879dffead566344675a79a43983a24fdf0
