### ISSUE TITLE
CACHE_TYPE = simple isn't thread safe so what type of cache should i use?

### ISSUE THREAD

**Issue by aaveidt** [sh4nks/flask-caching#136]
I see in the document:

> Set CACHE_TYPE to simple to use this type.
> 
> Uses a local python dictionary for caching. This is not really thread safe.

Why if itsn't thread safe why it set to be default cache type?
What type of cache is really thread safe?

The document is poor and doesn't explain anything.

**Comment by sh4nks** [comment]
It is set as the default caching type because it doesn't require any other services -- and it is easier for development.
