### ISSUE TITLE
support for versioned caches

### ISSUE THREAD

**Issue by havok2063** [sh4nks/flask-caching#149]
Does Flask-Caching support creating different caches (same or different cache backend) based on some chosen parameter.  My application is designed to work with versioned data sets, so all my of routes perform the same actions but return different data based on the current version set in the web interface.  Currently if I try to use `@cached`, it caches the route regardless of what dataset version is being used.  As a toy example...

```
@route('/dostuff/')
def dostuff():
    release = get_currently_set_release()
    data_specific = get_data_based_on_release(release)
    return render_template('index.html', **{'data': data_specific}) 
```
All of my routes do this, so this is something I need to at the global level, essentially have a `cache_releaseA`, `cache_releaseB`, etc.  Is there a way to do this without customizing the `cache_key` for every single route?

**Comment by sh4nks** [comment]
Not sure if I understood you correctly but I think you could solve your problem by initializing Flask-Caching a second time with an adapted configuration.
