### ISSUE TITLE
support for adding POST params into a cache key

### ISSUE THREAD

**Issue by havok2063** [sh4nks/flask-caching#150]
Some routes in my application are POST routes called via AJAX or an API.  The route itself has no arguments but I process the request form for input parameters.  Is there a way to add these parameters to the cache_key?  Toy example..

```
class DoStuff(FlaskView):
    @route('/dostuff/')
    @cache.memoize(timeout=300)
    def dostuff(self):
          args = process_request(request)
          objectid = args.get('objectid')
          ...
          ... do some stuff
          return jsonify(....)
```
I'd like to be able to have this route cached based on the input form parameters, like `objectid`.  Is there a way to do this?  It's not clear in the documentation.

**Comment by bimhud** [comment]
I'm having the same issue when trying to apply cache for POST request. @havok2063  Not sure if you find a way out? In the other scenario, I'm thinking to use a standalone redis cache for doing this, but not sure if I can use flask-caching?

**Comment by bimhud** [comment]
The other way out is to required unique key (UUID) as a part of request_path, that can be composed as an md5 hash on the post payload or params. So, if a client wants to get benefits from cache, they have to provide that key

**Comment by havok2063** [comment]
@bimhud  Yes I did find a way to do it.  I utilized the `make_cache_key` function on the `memoize` decorator.  See the [memoize API](https://flask-caching.readthedocs.io/en/latest/api.html#module-flask_caching.backends).   I had to dig through the API and source code to figure out how to use it.  Essentially you need to define a new function that creates the cache key and set that function as the `make_cache_key` function.  Inside that new function you can grab the Flask request arguments.  Here is an example using the above example route:

```
from flask import request 

# Flask route definition
class DoStuff(FlaskView):
    @route('/dostuff/')
    @cache.memoize(timeout=300)
    def dostuff(self):
          args = process_request(request)
          objectid = args.get('objectid')
          ...
          ... do some stuff
          return jsonify(....)

# create the cache key definition function
def get_dostuff_cache_key(*args, **kwargs):
    args = process_request(request)
    objectid = args.get('objectid')
    ... do some stuff
    key = 'custom_cache_key_{0}'.format(objectid)
    return key

# attach function 
DoStuff.dostuff.make_cache_key = get_dostuff_cache_key
```

**Comment by sh4nks** [comment]
See PR #159
