### ISSUE TITLE
[Suggestion] How to check that caching is working

### ISSUE THREAD

**Issue by simanacci** [sh4nks/flask-caching#151]
In the documentation, add a code snippet showing how one can check that the caching is working for various cache backends. For example redis.
`>>> import redis`
`>>> r = redis.Redis(host='localhost', port=6379, db=0)`
`# before running memoized function`
`>>> r.keys()`
`[]`
`>>> len(r.keys()`
`0`
`# after running the memoized function or cached view`
`>>> r.keys()`
`[b'flask_cache_JovMba3x3w8UnP76G4Mj05', b'flask_cache_t+0kJKm1Rfy8EtwHTX3Lo3']`
`>>> len(r.keys())`
`2`

**Comment by sh4nks** [comment]
Please use stackoverflow for questions like these.
Have a look at the tests to get a feeling how they are working: https://github.com/sh4nks/flask-caching/tree/master/tests
