### ISSUE TITLE
Magic number in SimpleCache and FileSystemCache

### ISSUE THREAD

**Issue by dAnjou** [sh4nks/flask-caching#155]
The [pruning](https://github.com/sh4nks/flask-caching/blob/b8e2fa6d3251dc60548751855d1d329eecef132a/flask_caching/backends/simple.py#L52) contains a magic number, it seems it deletes only every third entry: `idx % 3`.

I traced it back to the very beginning, there is no info there: https://github.com/mitsuhiko/zine/commit/3502607828b0f6ed136ed9ae74a09fa10f78a3ed#diff-b0794f264f02b7241cc1088d07e16659

I think this behavior should be reconsidered, tested, documented, and maybe even made configurable.

I'm also cross-linking the issue I created in pallets/cachelib (this is where the original code for the mentioned cache backends went after they got removed from werkzeug): pallets/cachelib#9.

Side note: since you're basically using the exact same code as in cachelib, maybe consider contributing back there (i.e. the tests), then pull in that library in.

**Comment by sh4nks** [comment]
Yes I have already considered it however I've never gotten around to do that.

Maybe you want to give it a try?

**Comment by lowne** [comment]
How about something like this:
```python
def _prune(self):
    n_entries = len(self._cache)
    if n_entries > self._threshold:
        now = time()
        soon = now + int(self.default_timeout * self.prune_oldest_fraction)
        n_toprune = int(n_entries * self.prune_oldest_fraction)
        expired, oldest, toprune = [], [], []
        for idx, (key, (expires, _)) in enumerate(self._cache.items()):
            if expires != 0 and expires <= now:
                expired.append(key)
            elif expires != 0 and expires <= soon:
                oldest.append(key)
            elif len(toprune) < n_toprune:
                toprune.append(key)
        for key in expired:
            self._cache.pop(key, None)
        n_entries = n_entries - len(expired)
        n_wanted = self._threshold - n_toprune
        if n_entries > n_wanted:
            for key in oldest:
                self._cache.pop(key, None)
        n_entries = n_entries - len(oldest)
        # if (many) entries are cached with timeouts longer than default, we might not be done yet
        n_more = n_entries - n_wanted
        if n_more > 0:
            for key in toprune[:n_more]:
                self._cache.pop(key, None)
```
with `prune_oldest_fraction` (e.g. `0.2`) going into `__init__`
