### ISSUE TITLE
DeprecationWarning due to invalid escape sequences

### ISSUE THREAD

**Issue by tirkarthi** [sh4nks/flask-caching#158]
```
./flask_caching/__init__.py:866: DeprecationWarning: invalid escape sequence \*
  """Deletes the specified functions caches, based by given parameters.
```

**Comment by sh4nks** [comment]
I am not getting this DeprecationWarning. What Python and Flask-Caching version do you use?

**Comment by tirkarthi** [comment]
It's on master branch with python 3.8. You can try `python3.8 -Wall -m py_compile flask_caching/__init__.py`
