### ISSUE TITLE
Constructing cache keys for selective invalidation

### ISSUE THREAD

**Issue by hiphamster** [sh4nks/flask-caching#160]
In my REST API i have a few long running calls, which i'd like to cache. The underlying data does not change frequently, and I'd like to be able to invalidate the cached result only when the data does change. It would be an easy task, if i could easily construct a cache key (perhaps even save and reuse it). Unfortunately, the function that constructs the key is defined inside the cached() decorator, and is not accessible outside. What's the rational behind that? The logic in key construction is not complicated, and i can write my own method to compute the key, but it would be better and less error-prone to use the same function. If there's a better way to selectively invalidate cache, i'm open to suggestions.

**Comment by komailrk** [comment]
I have tackled similar situations by adding a `recheck` flag which defaults to `False`.
The decorator looks at this and decides to not use the cache and instead run the original function and then cache the new value.

I can add some code examples on how I have done this shortly.

**Comment by sh4nks** [comment]
I am not planning to add this feature.

If someone wants to give it a try, I'll happily review the PR for it!
