### ISSUE TITLE
Cache after gzip

### ISSUE THREAD

**Issue by notpushkin** [sh4nks/flask-caching#161]
Hi there and first of all, thanks for your hard work on this extension!

Our app's responses are several MB in size, so we use caching (this extension) and compression (via [Flask-gzip]), naturally. However, the cache applies to responses before gzip, so it still takes a few seconds to re-compress them on each request. Is there a way to reverse the order in which extensions are working, i. e. compress the responses first and only then cache?

[Flask-gzip]: https://github.com/closeio/Flask-gzip

**Comment by gergelypolonkai** [comment]
Unfortunately, Flask-Gzip runs after the request is handled by your app, while the `@cached`/`@memoize` decorator is technically part of it. This means you can’t really tell `@cached`/`@memoize` to cache the gzipped response, but you might introduce a custom decorator that does the zipping before caching, like this:

```
@cached(…)
@compress_response
def my_view(a, lot_of, params):
    do_the_lengthy_thing()
```

**Comment by notpushkin** [comment]
Thanks! I'll share another solution in case somebody comes upon this issue with a similar problem:

```py
class CachedGzip(Gzip):
    def __init__(self, app, cache, *, cache_timeout=86400, **kwargs):
        self.cache = cache
        self.after_request = cache.memoize(timeout=cache_timeout)(
            self.after_request
        )
        self.after_request.make_cache_key = self._make_cache_key
        super().__init__(app, **kwargs)

    @staticmethod
    def _make_cache_key(f, response):
        return response.get_data()  # Perhaps would also need to mix status_code / headers in here
```
