### ISSUE TITLE
 ModuleNotFoundError: No module named 'werkzeug.contrib'

### ISSUE THREAD

**Issue by scottwilson312** [sh4nks/flask-caching#163]
Wekzeug released a new version and it's causing a crash.

``` ModuleNotFoundError: No module named 'werkzeug.contrib'```

**Comment by psalaberria002** [comment]
Same here. Any workaround?

**Comment by gergelypolonkai** [comment]
The quick and dirty workaround is to pin the `werkzeug` module to version `<1.0`

I try to devise a solution this week, but i canʼt promise anything.

**Comment by sh4nks** [comment]
Mhh I guess that issue resolved itself?

I can't reproduce it on my machine with ``Werkzeug==1.0.1``
