### ISSUE TITLE
Getting `redis.exceptions.ResponseError: value is not an integer or out of range`

### ISSUE THREAD

**Issue by docyx** [sh4nks/flask-caching#169]
I installed both Redis (latest stable version) and `redis` from PIP, and have a Redis server running with the `redis-server` command.

The Flask server itself starts up fine, but when I GET a route that is cached (almost all of the REST API routes), I get the error:

`redis.exceptions.ResponseError: value is not an integer or out of range`

I've tried running `cache.clear()` and I can't find anything on Google with the same error relating to Python/Flask.

More info:
- Running on Python 3.8 (most likely the culprit?)
- Frontend is Vue.js
- Using MongoDB and Pymongo for API data

**Comment by gergelypolonkai** [comment]
Could you give us a bit more details?

* In what environment do you run your app (Google App Engine, directly on a Linux host or container, etc.)
* What versions do you have?
** Flask
** Flask-Caching
** Redis Python module
** Redis server

Also, can you give us some traces on how to reproduce this? A short example app maybe? I’m asking for this as i can’t reproduce this with Python 3.8 on my local machine.
