### ISSUE TITLE
Calculate hit/miss ratio

### ISSUE THREAD

**Issue by zzzap** [sh4nks/flask-caching#17]
Often it is useful to know the hit to miss ratio for a particular view function, or maybe even for a memoization key, which includes both the function name and call parameters.

It would be very useful if `Flask-Caching` provided a way to register hooks that would be called on each hit and miss. It may also be useful to have a hook for errors thrown from the cache backend.

What do people think? I can work on a PR if there is chance that it would be accepted 😃

**Comment by sh4nks** [comment]
This sounds like a nice feature! There is definitely a chance that this is going to be merged. ;)

**Comment by zebpalmer** [comment]
+1 

I'm pushing metrics to a mongodb cappedCollection using before_request/after_request in many of my flask projects and would like to add cache hit/miss to that data. I'm still using Flask-Cache and came go github to fork & start a PR, but seeing how that project appears dead... looks like I'll be swapping to flask-caching first :) I'd definitely use this feature when available.

**Comment by danielunderwood** [comment]
I'm in a similar situation of sending off stats and would like cache hit/miss info per request. I don't know if this is something that should be included in the library or something that users should do. I'd be happy to open up a PR if it's something the authors think should be in the library.
