### ISSUE TITLE
Param default_timeout cannot be configured when using redis sentinel cache

### ISSUE THREAD

**Issue by AIweimd** [sh4nks/flask-caching#172]
As RedisSentinelCache inherit RedisCache, and RedisCache's param default_timeout is not the first kwargs , so RedisSentinelCache super init with one arg default_timeout cannot be configured well. 

`super(RedisSentinelCache, self).__init__(default_timeout)`

I suggest modified to kwargs for parent class RedisCache instance.

`super(RedisSentinelCache, self).__init__(default_timeout=default_timeout)`

Would appreciate help, thanks!

**Comment by sh4nks** [comment]
Nice catch!
