### ISSUE TITLE
ImportError: cannot import name 'import_string'

### ISSUE THREAD

**Issue by sonologic** [sh4nks/flask-caching#177]
Following the documentation at https://pythonhosted.org/Flask-Caching/ i tried adding a cache to my app:

```
import os

from flask import Flask, render_template, request
from flask_cache import Cache

config = {
    "DEBUG": True,          # some Flask specific configs
    "CACHE_TYPE": "filesystem", # Flask-Caching related configs
    "CACHE_DEFAULT_TIMEOUT": 300,
    "CACHE_IGNORE_ERRORS": False,
    "CACHE_DIR": os.path.join(os.path.dirname(__file__), 'cache'),
    "CACHE_THRESHOLD": 100000000,
    "CACHE_OPTIONS": "600",
}

app = Flask(__name__)

app.config.from_mapping(config)

cache = Cache(app)
```

Which results in an error starting the application:

```
FLASK_APP = app.py
FLASK_ENV = development
FLASK_DEBUG = 0
In folder /home/gmc/src/nfv/sso
/home/gmc/src/nfv/sso/venv/bin/python -m flask run
 * Serving Flask app "app.py"
 * Environment: development
 * Debug mode: off
Usage: python -m flask run [OPTIONS]

Error: While importing "app", an ImportError was raised:

Traceback (most recent call last):
  File "/home/gmc/src/nfv/sso/venv/lib/python3.6/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/home/gmc/src/nfv/sso/app.py", line 4, in <module>
    from flask_cache import Cache
  File "/home/gmc/src/nfv/sso/venv/lib/python3.6/site-packages/flask_cache/__init__.py", line 24, in <module>
    from werkzeug import import_string
ImportError: cannot import name 'import_string'


Process finished with exit code 2
```

These packages are installed:

Flask	1.1.2	1.1.2
Flask-Cache	0.13.1	0.13.1
Jinja2	2.11.2	2.11.2
MarkupSafe	1.1.1	1.1.1
Werkzeug	1.0.1	1.0.1
certifi	2020.4.5.2	2020.4.5.2
chardet	3.0.4	3.0.4
click	7.1.2	7.1.2
idna	2.9	2.9
itsdangerous	1.1.0	1.1.0
lxml	4.5.1	4.5.1
pip	20.1.1	20.1.1
requests	2.23.0	2.23.0
setuptools	47.1.1	47.1.1
urllib3	1.25.9	1.25.9

**Comment by komailrk** [comment]
The docs also tell you the package to install:
`pip install Flask-Caching`

The above installs the caching module provided by this project. The one you have is the original Flask caching no longer maintained.

Once you install it the import string is:
`from flask_caching import Cache`

Let me know if that doesn't work.

**Comment by sonologic** [comment]
*doh*

Yes, that fixes it. I should have paid more attention. Thanks!
