### ISSUE TITLE
Function having only *args and *kwargs fails

### ISSUE THREAD

**Issue by PonteIneptique** [sh4nks/flask-caching#18]
In the context of my plugin flask-capitains-nemo ( https://github.com/Capitains/flask-capitains-nemo ), I am trying to get memoized a certain list of functions. I currently cache dynamically these one through : 

```python
        if self.cache is not None:
            for func, instance in self.cached:
                setattr(instance, func.__name__, self.cache.memoize()(func))
```

It works well, as long as I don't cache functions that have no enforced args or kwargs schemes but are actually route dispatcher : 
 
```python
def render(self, template, **kwargs):
```

will always create the key : `flask_nemo.Nemo.render('main::collection.html',){}` as the output of self._memoize_kwargs_to_args will not work with a `**kwargs` system. It is most likely the result of the use of `get_arg_names`. which will find only one defined arg.

I'll be trying to propose a fix for this issue.

**Comment by sh4nks** [comment]
> I'll be trying to propose a fix for this issue.

Thanks, could you also add a little test for it?

**Comment by PonteIneptique** [comment]
Well, it would not be a contribution if there wasn't ;)

**Comment by PonteIneptique** [comment]
Just so I know : what timezone are you in ? Just to know where I can expect answer and not :)

**Comment by sh4nks** [comment]
I am in CET. I am off of work today so I have some time to spent on my projects :)

**Comment by PonteIneptique** [comment]
It's good to find someone in CET ! Patch will be coming in the next hour or so

**Comment by PonteIneptique** [comment]
Thanks for the support ! Was really cool to be in sync ;)

**Comment by sh4nks** [comment]
New release is out :)
