### ISSUE TITLE
improve observability

### ISSUE THREAD

**Issue by twosigmajab** [sh4nks/flask-caching#182]
It would be useful to record basic events and metrics (cache size, hits, misses, evictions, etc.). I took a look through the docs and the code and didn't see anything about this. Even just logging these events when they occur at debug level would be a big improvement, to give users the option of having some more visibility into what the cache is actually doing. What do you think?

P.S. Thanks for maintaining Flask-Caching!

**Comment by sh4nks** [comment]
While I think having such a feature might be helpful for debugging I have no plans implementing such feature.

**Comment by twosigmajab** [comment]
The minimum required here is just a matter of adding a few `logger.debug` calls. Would you at least accept a PR?

**Comment by sh4nks** [comment]
Yeah, I'd accept a PR :-)

**Comment by jab** [comment]
Thanks for considering a PR for this, @sh4nks! Please see #203. Hope this is helpful!
