### ISSUE TITLE
Error in how FileSystemCache counts number of files

### ISSUE THREAD

**Issue by fnordian** [sh4nks/flask-caching#188]
The set operation in `flask_caching/backends/filesystemcache.py` increases the file count even if the item exists already. This leads to a higher assumed count of files and to more prunes than necessary.

**Comment by Kl000s** [comment]
Is this still open? I would like to give it a try.

**Comment by sh4nks** [comment]
Yeah, I'm happy to review a PR if you want to submit one :-)

**Comment by Kl000s** [comment]
Just submitted the PR :-)
