### ISSUE TITLE
redis.exceptions.ResponseError: value is not an integer or out of range

### ISSUE THREAD

**Issue by Directory** [sh4nks/flask-caching#199]
This is a duplicate of #169 . However that incredibly kind and helpful developer was nice enough to close the issue without providing any feedback at all about what he ended up doing therefore wasting my time. Heres the full traceback.
```python
Exception possibly due to cache backend.
Traceback (most recent call last):
  File "/redacted/lib/python3.8/site-packages/flask_caching/__init__.py", line 463, in decorated_function
    self.cache.set(
  File "/redacted/lib/python3.8/site-packages/flask_caching/backends/rediscache.py", line 130, in set
    result = self._write_client.setex(
  File "/redacted/lib/python3.8/site-packages/redis/client.py", line 1822, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/redacted/lib/python3.8/site-packages/redis/client.py", line 901, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/redacted/lib/python3.8/site-packages/redis/client.py", line 915, in parse_response
    response = connection.read_response()
  File "/redacted/lib/python3.8/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range
```
As you can see i am using python3.8 in a virtual envirement.
I have the current newest versions of flask, redis.py, redis, and this library.
Flask is currently being deployed with gunicorn and the gevent worker. 

Heres the setup.
```python
cache_config = {
    'CACHE_TYPE': 'redis',
    'CACHE_REDIS_HOST': 'localhost',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 0,
    'CACHE_REDIS_PASSWORD': 'password123'
}
cache = Cache(app, config=cache_config)
```
I initially was only setting CACHE_REDIS_URL but then tried setting these variables individually. As you can see, it makes no difference. Any help/response some time as soon as possible would be really greatly appreciated as this is needed in production, like, right now.

from my 5 seconds of googling, this seems to be some internal bug in the library with which redis classes its using or something.

**Comment by Directory** [comment]
still waiting

**Comment by sh4nks** [comment]
Could you provide a minimal reproducible example application? This would be really helpful for debugging this issue.

**Comment by Directory** [comment]
its literally just hello world but deployed for production and the same issue occurs on a new install of ubuntu server.
```py
from flask import Flask
import time
from flask_caching import Cache
app = Flask(__name__)
cache_config = {
    'CACHE_TYPE': 'redis',
    'CACHE_REDIS_HOST': 'localhost',
    'CACHE_REDIS_PORT': 6379,
    'CACHE_REDIS_DB': 0,
    'CACHE_REDIS_PASSWORD': 'password123'
}
cache = Cache(app, config=cache_config)

@app.route('/')
@cache.cached(timeout=30)
def ihgdbfoiweuhybfghoi():
    return str(time.time())
```
deploy with gunicorn, in my case im using gevent.
