### ISSUE TITLE
Thanks Sh4nks

### ISSUE THREAD

**Issue by xealot** [sh4nks/flask-caching#2]
Not an issue, obviously.

I have been concerned about Flask-Cache for a while and it's complete lack of updates. Has the original author been in communication at all? Can the repo be shared/transferred so that we don't need people to update dependencies?

Either way I'll be attempting to use your fork, thanks for your time.

**Comment by sh4nks** [comment]
Hey, thanks! I was actually waiting until one steps up and makes a proper fork but nobody really did.. so I did :).
I didn't reach out to him personally but it seems that the author hasn't been in communication for quite some time now. I think this is only possible if the author permits it.

**Comment by xcash** [comment]
A big thanks from us too! :+1: We'll be using your fork!

**Comment by asteinlein** [comment]
Wanted to say thanks as well, awesome pushing this out! 

I think this is fine given the original license, however I think it would be a good idea to reach out to the original author to get an explicit OK, possibly even to transfer ownership of the original name/repo. Worst that can happen is you don't get a response at all... :)

**Comment by bart3005** [comment]
As far as I can see there has been no comms form the original author. A couple of people have reached out to no avail.

**Comment by rlam3** [comment]
So moving forward this project is replacing Flask-Cache?

**Comment by xcash** [comment]
@rlam3 yep.
