### ISSUE TITLE
instance token as a function for caching methods?

### ISSUE THREAD

**Issue by hoopes** [sh4nks/flask-caching#20]
Hi,

I'm working on an app where I'd like to cache the result of a method, no matter which instance of the object it is. 

For example, 

    class Thing(object):
        @cache.memoize
        def method(self, a, b):
            ...do some work...

    obj1 = Thing()
    obj2 = Thing()

    val1 = obj1.method(1,2)
    val2 = obj2.method(1,2)  # cached!

It seems like `flask-caching` is keeping a "version" of the function to be cached. (In `_memoize_version`, which gets it from `function_namespace`). Currently, it defaults to "if i have an instance of an object, its token is `repr(instance)`", which is something like `<abc.object at 0xabcdef123456>`. I'd like to add a function (called `instance_token`?) that takes an instance and by default, returns `repr`, but could be overridden to return something based on the class module/name. 

So my extension could look like:

    class MyCache(Cache):
        def instance_token(self, inst):
            cls = inst.__class__
            mod  = cls.__module__
            name = cls.__name__

            return '{}.{}'.format(mod, name)

Does that make sense? I certainly don't have the depth of experience of actually *writing* this library, so if there's some facet of python (multi-threading?) that makes it not feasible, I can certainly work around it. If it does seem feasible, I'll take a run at a PR, if it would be helpful.

**Comment by sh4nks** [comment]
The cache would then return the results of both instances, right?

I can't think of anything right now that wouldn't make it feasible.
Could you also add some tests if you are still interested in this?
