### ISSUE TITLE
Access returned value in unless callback

### ISSUE THREAD

**Issue by jinyus** [sh4nks/flask-caching#200]
I am trying to bypass caching based on the result that the function returned (In this case, it won't cache if the function returns an empty list). Is this possible?

"""
@cache.memoize(timeout=86400,unless=lambda: result == [])
def get_followers(user_id) -> List[User]:
"""

**Comment by sh4nks** [comment]
If result is an empty list, your example should work.
Check out this function to get a better understanding how it works: https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L743-L761
