### ISSUE TITLE
Compression for cached values

### ISSUE THREAD

**Issue by mkhorton** [sh4nks/flask-caching#205]
Is it possible to compress values before storing them in the cache (and decompressing them on retrieval)? If not, would there be an appropriate place to add a hook for this?

I'm trying Flask-Caching with a redis deployment, and it looks like a significant amount of memory could be saved by compressing the cached values, and uncompressing them when retrieved from the cache.

Performing the compression in the body of the function is not appropriate, since other parts of the web app would require un-compressed values to be returned by the relevant functions.

Thanks for a great library!

**Comment by sh4nks** [comment]
You could implement a wrapper around the cache object that handles that for you and then use the wrapped cache object to retrieve and set the values.

**Comment by mkhorton** [comment]
Thanks for the response. You mean wrap `@cache` and `@memoize` using functools, to create new decorators? That sounds a lot easier than I was expecting -- is there anything special about Flask-Caching to know about before implementing?

**Comment by sh4nks** [comment]
I haven't thought about wrapping the decorators but I guess that would work as well.

I thought about wrapping the ``cache.set``, etc functions (https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L246-L282). Another possibility would be to create a new redis backend and implement it directly in the backend.
