### ISSUE TITLE
Import Error When Using rediscluster

### ISSUE THREAD

**Issue by DustinMoriarty** [sh4nks/flask-caching#206]
When CACHE_TYPE is set to rediscluster, an import error occurs.

```bash
  File "/path/to/lib/python3.8/site-packages/flask_caching/__init__.py", line 220, in _set_cache
    raise ImportError(
ImportError: rediscluster is not a valid Flask-Caching backend
```
Upon further inspection, it appears that for some reason rediscluster cannot be imported from flask_caching.backend.

```python
>>> from flask_caching.backends import redis
>>> redis
<function redis at 0x7fcf55339af0>
>>> from flask_caching.backends import rediscluster
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'rediscluster' from 'flask_caching.backends' (/path/to/lib/flask_caching/backends/__init__.py)
However, rediscluster should be a function at flask_caching/backends line 120 of release 1.9.0. I am still trying to determine what is different between redis and rediscluster which would make redis cluster not import.
```

It should be noted that this error only occurs when the package is installed from a build. It does not occur when the package is installed from source in editable mode.

**Comment by DustinMoriarty** [comment]
Also it appears that the __all__ dunder does not include rediscluster.

```python
>>> import flask_caching.backends
>>> flask_caching.backends.__all__
('null', 'simple', 'filesystem', 'redis', 'redissentinel', 'uwsgi', 'memcached', 'gaememcached', 'saslmemcached', 'spreadsaslmemcached')
```

**Comment by DustinMoriarty** [comment]
Now I see that this is a case where the documentation is ahead of the release. 1.9.0 does not contain the rediscluster addition. However, rediscluster is documented in [readthedocs](https://flask-caching.readthedocs.io/en/latest/#redisclustercache). I am not sure if the intent is to have the docs ahead of the latest release or not.

**Comment by sh4nks** [comment]
Ah yeah right. I'll try to release a new version in the next couple of days and setup some sort of stable docs.

**Comment by mahdiqb** [comment]
just ran into the same issue, @sh4nks is the upcoming release expected soon? Thanks!

**Comment by sh4nks** [comment]
See answer in https://github.com/sh4nks/flask-caching/issues/216#issuecomment-787488509
