### ISSUE TITLE
Memoization per entire request

### ISSUE THREAD

**Issue by iairsalem** [sh4nks/flask-caching#207]
Hello,

I'd like to make use of memoization not using a timeout but on a per-request basis (on a same request, function might get called more than once, I want that to be memoized).

As a workaround I modified the timeout so at the end of the request 30 seconds would be subtracted. I thought that by doing that, I would be effectively enabling a per-request (timeout=29) memoization. Now I realized that:
1) it will memoize for other requests (happening at the same time) as well.
2) it might de-memoize stuff based on other requests ending (not sure about this, please ignore).

I'm not sure if this is currently handled in any way, or if this is a feature-request.

Thank you.

**Comment by gergelypolonkai** [comment]
Iʼm not sure i would use caching for that. Request globals (`from flask import g`) and local proxies are exactly for this purpose.

**Comment by iairsalem** [comment]
@gergelypolonkai I think there's definitely a use case for memoization per request (with one commit per request) . I've made a pseudo-cache before knowing about flask-caching, but now that I've found that flask-caching exists it doesn't make sense to make a cache per function.
Cache with a timeout makes more sense for static content. However, if you memoize for a certain amount of time, you are never sure the database hasn't changed. On the other hand, we can assume the data would stay more stable on the same request (we need to draw a line, and if it's within the same transaction, it's also safer to assume data will be the same).

**Comment by gergelypolonkai** [comment]
I agree, but i still think flask-caching is not the way to go here, as it would save your function result to a backend (Redis, memcached, etc). Setting a timeout for such ched values is tricky, as you canʼt know how long serving the request will take. You may try adding the request itself to the memorize key (as if it was a parameter to your function) but in that case this value will linger in your backend for *some time* (again, for how long?), no one using it.

Hence my suggestion to use `flask.g`, as it gets destroyed at the end of the request, regardless of execution success/failure.
