### ISSUE TITLE
Provide own backend instead of using config

### ISSUE THREAD

**Issue by PonteIneptique** [sh4nks/flask-caching#21]
Hi there, it's me again.
One thing I'd like to do is to be able to provide my own backend object instead of going through config with a keyword argument `backend` on `__init__()`. This way I can share or have specific backend objects across my code base :)

If this feature is okay, I'll put in the work. Question is : would type checking be required for werkzeug.contrib.BaseCache ?

Cheers

**Comment by sh4nks** [comment]
Couldn't you just instantiate another instance with a different backend? 

> Question is : would type checking be required for werkzeug.contrib.BaseCache ?

I am not sure if I understand you correctly..
Do you mean if you have to subclass BaseCache?

**Comment by sh4nks** [comment]
https://pythonhosted.org/Flask-Caching/#custom-cache-backends

> You are able to easily add your own custom cache backends by exposing a function that can instantiate and return a cache object. CACHE_TYPE will be the import string to your custom function. It should expect to receive three arguments.
> 
> - app
> - args
> - kwargs
>
> Your custom cache object must also subclass the werkzeug.contrib.cache.BaseCache class. Flask-Caching will make sure that threshold is already included in the kwargs options dictionary since it is common to all BaseCache classes.
