### ISSUE TITLE
Please make subclassing cache backends easier

### ISSUE THREAD

**Issue by ThiefMaster** [sh4nks/flask-caching#213]
I tried using `app.config['CACHE_TYPE'] = 'mypackage.MyRedisCache'` to use a custom subclass of the redis cache backend, and was then surprised that things didn't work. Until I realized that this shouldn't point to the class itself, but the function from `backends/__init__.py`... so if I want to use a custom subclass, I now need to copy&paste about 25 lines of code from there into my application which is of course rather awful.

It would be nice if this factory function was a classmethod on the actual backend class.

**Comment by sh4nks** [comment]
I fully agree! I don't have much time right now as I became a dad recently :-). If you want to submit a PR I'd gladly merge it.

**Comment by gergelypolonkai** [comment]
@ThiefMaster while this gets fleshed out, you can copy the corresponding function from `backends/__init__.py` and set `CACHE_TYPE` to the path of that function.

But indeed, this could work much better, if we can make the `__init__` of the backend classes uniform.

**Comment by sh4nks** [comment]
This is implemented now thanks to @gergelypolonkai. I have published a new version which includes this change. In the future, this will be the only way to use backends.
