### ISSUE TITLE
Storing of gzipped content in cache.

### ISSUE THREAD

**Issue by o1da** [sh4nks/flask-caching#22]
Is there a way to store compressed data in cache backend?

I use Memcached with pylibmc, I cache a product list page where much of content is being repeated - It can have 1MB as plain text but something like 60KB gzipped. So it is a wasting of Memcached storage to store it. It can even have a problem with Memcached default max size for an item (1MB) - with `python-memcache` it seemed to me that `flask-caching` simply didn't work :) `pylibmc` at least throw an exception with max size problem.

Can the Flask itself help somehow? Maybe returning gzipped result of the view function? But it wouldn't be a solution for `memoize()` either.

Or is it possible and reasonable to add compression there https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L351 and decompression there https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L340 and control it by configuration?

**Comment by sh4nks** [comment]
I am not sure if this is a problem with Flask-Caching - It is actually just a wrapper around werkzeugs `werkzeug.contrib.cache` module. Does `python-memcache` support it? We could add a backend for it, if this library supports it. Or maybe, just changing a few config values would work?

Feel free to open a PR for it. :)

**Comment by o1da** [comment]
It is not a problem with Flask-Caching itself it behaves correct but I mean it as a question if it makes sense to create enhancement for Flask-Caching to solve this general issue. I haven't found anything about zip in `pylibmc` documentation (I don't use `python-memcache` because `pylibmc` seems to be better for me).

Ok, I will prepare PR :)
