### ISSUE TITLE
template docs for keys suggestions

### ISSUE THREAD

**Issue by illume** [sh4nks/flask-caching#23]
Hello,

I think the docs for template caching could be improved somehow...

1) Describing that keys control if something should be fetched from cache or not. If the keys change, then the content is not cached. I'm not sure of the best wording, but on first reading the documentation it wasn't clear to me what keys were for.

2) Show an example of using multiple keys. I had to discover that a comma is required.
```
  {% cache 60*5, project_id | string(), release_id | string() if release_id else '' %}
```

3) It seems int works for the first key, but the other keys require a string. Also it seems None is not safe here. I'd expect a key of None to not use the key.

best regards,

**Comment by sh4nks** [comment]
Yeah feel free to open a PR for this! :)
