### ISSUE TITLE
DeprecationWarning: flask_caching.backend is deprecated

### ISSUE THREAD

**Issue by bmalbusca** [sh4nks/flask-caching#248]
Hi, I'm receiving a deprecation Warning around of flask_caching. There is any suggesting to fix the usage of flask_caching for future?

The Warning:
```
python3.8/site-packages/flask_caching/__init__.py:237: DeprecationWarning: Using the initialization functions in flask_caching.backend is deprecated.  Use the a full path to backend classes directly.

```

The code:
```
from flask_caching import Cache
...
app.config['CACHE_TYPE'] = 'simple'
app.cache = Cache(app)

```

**Comment by gergelypolonkai** [comment]
I agree the message is a bit misleading, i’ll rephrase it soon.

Meanwhile, see the [relevant section of the docs](https://flask-caching.readthedocs.io/en/latest/#set-up). In this specific case, you can simply change from the old name (`simple`) to the class name behind it (`SimpleCache`).
