### ISSUE TITLE
TypeError: sequence item 0: expected str instance bytes found

### ISSUE THREAD

**Issue by reubano** [sh4nks/flask-caching#25]
```bash
Exception possibly due to cache backend.
Traceback (most recent call last):
  File "https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py"
    rv = self.cache.get(cache_key)
  File "https://github.com/sh4nks/flask-caching/blob/master/flask_caching/backends/clients.py"
    return self._get(key)
    serialized = ''.join([v for v in result if v is not None]
TypeError: sequence item 0: expected str instance, bytes found
```

Python 3.6.0
Flask-Cache==0.13.1

**Comment by reubano** [comment]
The error happens on heroku but not my laptop.

**Comment by reubano** [comment]
Also `key_prefix` is `request.url`.

**Comment by sh4nks** [comment]
I am having a hard time to reproduce this. What did you do that this happens?

**Comment by reubano** [comment]
Nothing I haven't normally done. Just using `@cache.cached()` with the `spreadsaslmemcached` backend. I even tested the original plugin and got the same error. You can see how I solved the problem [here](https://github.com/reubano/mezmorize/blob/master/mezmorize/backends.py#L164-L167). I assumed it was a py2/py3 thing. But now I suspect it's a difference in the memcache libs. Maybe heroku's version has some setting that triggers bytes.

**Comment by sh4nks** [comment]
Could you provide a test that fails? btw, how is ``mezmorize`` different from Flask-Caching? Maybe we should put our resources together instead of maintaining a slightly different version of Flask-Cache?

**Comment by reubano** [comment]
`mezmorize` is basically just the memoization part of `Flask-Cache` and also without the flask dep. It's meant to memoize regular functions (similar to `lru_cache`), not to be used on routes. I haven't gotten around to writing up documentation yet. Sure, I'd be open to collaborating since it really is just a subset. It should be possible to figure out a way to support both use cases in the same codebase.

**Comment by reubano** [comment]
My project is fairly large so extracting a base test case may take a while. Could you post the code you tried using to reproduce the issue? I could then work from that.

**Comment by sh4nks** [comment]
I am using it with redis at forums.flaskbb.org and I never ran into this issue (same for simple). I haven't tried it with memcache but I could imagine that it's a problem with the memcache libs as you have said. 

I am not seeing a huge difference apart from the ``@cache.cached`` decorator. If I have a some spare time this weekend I'll try to put something together (i.e. Flask-Caching simple being a wrapper around ``mezmorize`` with an additional decorator for routes.).
