### ISSUE TITLE
Arrangement of Arguments in Functions

### ISSUE THREAD

**Issue by sh4nks** [sh4nks/flask-caching#27]
Any ideas why the arrangement of the arguments in functions matters in Python > 3.3 (I tested it with Python 3.6 but the tests for Python 3.5 are also failing, so it probably can also appear in Python 3.4)?

For example, to fix the kwargs tests I had to re-arrange the arguments (in unittest method ``test_10a_arg_kwarg_memoize_var_keyword`` [L354-L368](https://github.com/sh4nks/flask-caching/blob/master/test_cache.py#L354-L368))
**from**
```python
assert f(1, 2, d=5, e=8) == f(1, 2, e=8, d=5)
assert f(1, b=2, c=3, d=5, e=8) == f(1, 2, e=8, d=5, b=2, c=3)
```

**to**
```python
assert f(1, 2, d=5, e=8) == f(1, 2, d=5, e=8)
assert f(1, b=2, c=3, d=5, e=8) == f(1, b=2, c=3, d=5, e=8)
```

**Comment by xcash** [comment]
In Python 3.5.2 there's no problem in keywords order.

```
>>> def a(arg1=None, arg2=None):
...     return arg1+arg2
... 
>>> assert a(arg1=1, arg2=2) == a(arg2=2, arg1=1)
>>> 
```
