### ISSUE TITLE
Support for redis sentinel / multi-instance redis installation

### ISSUE THREAD

**Issue by eleweek** [sh4nks/flask-caching#28]
Hi! What would be the best way to approach using Flask-Caching with Redis Sentinel? It doesn't look like that werkzeug's `RedisCache` supports Sentinel.

I'm willing to work on a PR for the support.

**Comment by eleweek** [comment]
Ping @sh4nks

**Comment by sh4nks** [comment]
I haven't heard about Redis Sentinel yet so I am not much of a help here but I am definitely interested in a PR if you want to work on it! I'll have a look at it after the easter holidays.
Sorry for the late (and not really helpful) reply.

**Comment by eleweek** [comment]
It seems like underlying level(`werkzeug`) doesn't seem to support sentinel, so adding support for redis sentinel may be tricky. I'll look into what can be done here.

**Comment by sh4nks** [comment]
You could create your own caching backend if you really need this feature. Flask-Caching just ships with the default ``werkzeug.contrib.cache``ing backends.
