### ISSUE TITLE
Using Flask-Caching with Flask-Restful

### ISSUE THREAD

**Issue by arkady** [sh4nks/flask-caching#3]
I'd like to use Flask-Caching in my Flask-Restful app.  I wanted to take advantage of `make_cache_key` property that gets added to the decorated method, but could not figure out how to make it work.  Any ideas?

```
from flask import Flask, url_for
from flask_restful import Api, Resource
from flask_caching import Cache

app = Flask(__name__)
api = Api(app)
cache = Cache(app, config={'CACHE_TYPE': 'simple'})

@api.resource('/whatever/')
class Foo(Resource):
    @cache.cached()
    def get(self, param):
        return expensive_db_operation()

    def post(self):
        ## Before I update the DB, I'd like to invalidate the result of get().
        ## I ended up with this ugly thing... is there a better way?
        cache.delete('view/' + url_for('foo'))

        update_db_here()
        return something_useful()
```

**Comment by sh4nks** [comment]
Hey! So if I understood your problem correctly, you want that the decorator also takes the Request Method into account right? I am handling it like [this](https://github.com/sh4nks/flaskbb/blob/master/flaskbb/user/models.py#L339-L381) and it actually works quite well. Sorry for my late reply btw, I was on vacation ;)

**Comment by erwinyusrizal** [comment]
@sh4nks similar to @arkady is it possible to cache the view (in my case I use cache header) and memoize in my model?

**Comment by erwinyusrizal** [comment]
I end up with your solution above
