### ISSUE TITLE
A weired problem, after deleting, then cache does not work

### ISSUE THREAD

**Issue by tim-hub** [sh4nks/flask-caching#30]
<pre>
@app.route('/cache/')
@cache.memoize(timeout=0)
def test_cache():
    print 'cache'
    import random

    return "%s" %random.randint(0,9)

@app.route('/delete-mem/')
def clear_one():
    cache.delete_memoized(test_cache)
    return 'clear one'
</pre>

The cache mode is simple.

**the problem is after I delete the cache `clear_one()`, when I run `test_cache()`, everytime(every reloading the page), it give a new number.**

**Comment by sh4nks** [comment]
Try setting it to None or something bigger than 0. You are literally caching it for 0 seconds.
https://pythonhosted.org/Flask-Caching/#flask_caching.Cache.memoize
> Parameters:	
> timeout – Default None. If set to an integer, will cache for that amount of time. Unit of time is in seconds.
