### ISSUE TITLE
A small question about delete cache

### ISSUE THREAD

**Issue by tim-hub** [sh4nks/flask-caching#31]
How to delete a spercific cache.

I mean if `cache.clear()`, it will remove all cache. what about if I want to delete only one cached route.

ref: https://stackoverflow.com/questions/36180066/flask-cache-equivalent-of-delete-memoized-for-clear

**Comment by sh4nks** [comment]
I am not sure if I understood you correctly. The question you asked is already answered in the stackoverflow post you linked. 

For example, this is how I delete a cache (similar to the answer in the SA post):
Have a look here: https://github.com/sh4nks/flaskbb/blob/master/flaskbb/user/models.py#L371
and this is how we 'invalidate' (i.e. delete a specific cache): https://github.com/sh4nks/flaskbb/blob/master/flaskbb/user/models.py#L394

please use stackoverflow for questions like this in the future.
