### ISSUE TITLE
Set cache depending on result

### ISSUE THREAD

**Issue by chrisdebug** [sh4nks/flask-caching#34]
I'm using flask-caching to cache the results of an api endpoint. I'd like to set the cache depending on the result. Ex: Don't set the cache if the response is something like {"error": "message"}
What's the best way to do this? Should I override a method? If so, which method?

**Comment by sh4nks** [comment]
You could for example create a custom cache key method.
See https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L306

Please use stackoverflow for questions like this in the future.
