### ISSUE TITLE
Please create git tags for each version

### ISSUE THREAD

**Issue by Croydon** [sh4nks/flask-caching#36]
This makes it easier to work with a specific version of the extension :)

**Comment by sh4nks** [comment]
Damn, forgot about it. I created one for 1.3.0.

**Comment by gordol** [comment]
this still isn't done.... and hasn't been doing going forward. why not??

**Comment by gordol** [comment]
or at least use github releases, or *something*... right now it's impossible to know what commit a pypi release is pegged to.

**Comment by Croydon** [comment]
There are tags, but it's lagging behind. There is no tag for 1.4.0 (and maybe other versions I haven't checked out) @sh4nks

**Comment by sh4nks** [comment]
> or at least use github releases, or something... right now it's impossible to know what commit a pypi release is pegged to.

039d8aef5e3ebbb70c0f679f4e4452f80f594dd1 this commit is published on pypi as 1.4.0
