### ISSUE TITLE
Question/consideration: Python 3.6 and consistent ordering, insertion preservations

### ISSUE THREAD

**Issue by lily-mayfield** [sh4nks/flask-caching#39]
One of the things that has changed in Python 3.6 is consistent ordering and insertion preservation for datatypes which are hashed (dict, set, etc.). It may be possible to leverage this to your advantage to skip having to sort query string parameters with `sorted()` in Python 3.6.

I think this may be completely solved by the fact that using `sorted` is initiated by `query_string=True`, but then it should be called `legacy_cache_key_fix` or something?

Just brainstorming, something I thought of... I'll try to come back and elaborate/update the issue.

**Comment by ChaoticMind** [comment]
Hey, 

The Python 3.6 [release notes](https://docs.python.org/3/whatsnew/3.6.html#whatsnew36-compactdict) explicitly say that relying on the dict sorting order should be avoided (at least until their implementation is part of an official spec).

So I therefore think a feature relying on it for caching purposes shouldn't be incorporated (if I understand your suggestion correctly).
