### ISSUE TITLE
add/set/etc should return the results of the functions they wrap 

### ISSUE THREAD

**Issue by dev-zero** [sh4nks/flask-caching#4]
When calling `cache.add` or `cache.set`, the result is currently lost. This makes it necessary to call `cache.cache.add` instead to get the result of the underlying cache implementation (and to be able to implement a cache-based locking mechanism using `cache.add`).

Since those functions are bare wrappers around a caching implementation (Werkzeug most of the time), I expected them to also return the results.

**Comment by sh4nks** [comment]
Thanks for reporting & sending a PR!
