### ISSUE TITLE
Flask Caching With Sentinel 

### ISSUE THREAD

**Issue by JLiu1272** [sh4nks/flask-caching#40]
I am trying to enable Flask Cache. We are currently using redis-sentinel to handle failover issues, and to increase concurrency performance. However, it seems this way of caching is more difficult to resolve than imagine. Perhaps, you guys can help me. 

```
from flask_caching import Cache
from redis import StrictRedis
from werkzeug.contrib.cache import BaseCache
from redis.sentinel import Sentinel
from app import Config

class SentinelCache(BaseCache):
   def __init__(self, key_prefix=None, **kwargs):
        BaseCache.__init__(self, default_timeout=300)
        host = str(kwargs['host'])
        port = str(kwargs['port'])
        #print(host + ":" + port)
        print(Sentinel([{host:host, port:port}]))
        #Setting self client to be a sentinel 
        self._client = Sentinel([{host:host, port:port}])

def sentinel(app, config, args, kwargs):
  #Get master 
   sentinel = Sentinel(list(map(lambda x: (x.split(':')[0], int(x.split(':')[1])), Config.get('REDIS_SENTINEL_SERVERS').split(','))))
   master = sentinel.discover_master('rdwhizz')
   config['SENTINEL_SERVERS'] = master
   kwargs.update(dict(
      host=master[0],
      port=master[1]
   ))
   print(kwargs)
   return SentinelCache(*args, **kwargs)

cache = Cache(config={'CACHE_TYPE':'app.cache.sentinel'})
```

Here is what I have currently. We were able to retrieve the master host and port. But what we are  are unable to do is sub class Base Cache to enable Sentinel Caching.  

Thank you!

**Comment by sh4nks** [comment]
Sorry for my late reply.

Did you solve the problem? Can I still help you somehow?

**Comment by sh4nks** [comment]
Checkout this branch for basic redis-sentinel support: https://github.com/sh4nks/flask-caching/tree/redis-sentinel

Things to TODO/investigate:
- What happens when you want to use 2 master? Is this even possible?
- Add documentation about the new backend
- Testing with more than one sentinel

This is the config I used to test sentinel with:

```
sentinel monitor mymaster 127.0.0.1 6379 2
sentinel down-after-milliseconds mymaster 60000
sentinel failover-timeout mymaster 180000
sentinel parallel-syncs mymaster 1
```

**Comment by JLiu1272** [comment]
Hi yes, I figured it out. But thank you so much for adding that. I am sure it will be useful for some others as well.

**Comment by gergelypolonkai** [comment]
Will the redis-sentinel branch be merged in the foreseeable future?

To address your first TODO/investigate point, AFAIK you can’t have more than one Redis master; in fact, that’s why sentinel is needed at all.

If it’s only the documentation and testing part is missing, i can give it a go.

**Comment by sh4nks** [comment]
> If it’s only the documentation and testing part is missing, i can give it a go.

That would be awesome - I really do appreciate any help :-)
