### ISSUE TITLE
Configurable key function

### ISSUE THREAD

**Issue by jkomusin** [sh4nks/flask-caching#44]
I have a need to configure a function at the app level which would transform keys passed in to get/set calls on the cache prior to them being sent to the backend. Specifically, this would allow us to md5 hash keys prior to them getting to memcached to avoid hitting the 250-character limit on keys there while keeping our application-facing keys readable and sufficiently verbose.

Django has a hook similar to this called 'KEY_FUNCTION': https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-CACHES-KEY_FUNCTION so this would also aid in cache sharing between Django and Flask apps (something we would also like to do).

Do others think this would be useful? The key prefix could also be provided to the function similarly to Django's implementation.

**Comment by sh4nks** [comment]
I'll gladly review a PR for this! :)

**Comment by jkomusin** [comment]
Sorry I totally forgot about this. We ended up doing away with our cache prefixing and so never needed to solve this. As such it's not really on my radar anymore (which may be clear by the delay in a PR).
