### ISSUE TITLE
[Question] Why do the file backend create so many cache files?

### ISSUE THREAD

**Issue by EpocDotFr** [sh4nks/flask-caching#46]
First, thanks for continuing the development of Flask-Cache. It's a great piece of software.

So, I'm using the `memoize` decorator with a 60 seconds timeout on a method in a class. Data returned by this method may differ between each timeouts (calls). This class has a fixed `__repr__` (i.e always the same string). 

I noticed that a cache file is created each time the timeout was reached. I.e the first call creates a file with cached data, then on the second call when the timeout is reached, data is fetched again and another file is created with this data (the olds ones never gets deleted). This could lead to a folder with thousands of useless files.

Why this behavior? Aren't cache files supposed to be reused?

**Comment by sh4nks** [comment]
See http://werkzeug.pocoo.org/docs/0.12/contrib/cache/#werkzeug.contrib.cache.FileSystemCache.

> threshold – the maximum number of items the cache stores before it starts deleting some.

You could try to modify the threshold to reduce the files in your caching folder. I don't know why they chose to use a behaviour like this. 

>  Aren't cache files supposed to be reused?

My guess is that they want to ensure the data integrity.

**Comment by EpocDotFr** [comment]
> You could try to modify the threshold to reduce the files in your caching folder. I don't know why they chose to use a behaviour like this.

Thank you for the information, TBH I didn't even read the doc of the underlaying backend ^^"

> My guess is that they want to ensure the data integrity.

Or maybe version the cached data?

Anyway, thanks!

**Comment by sh4nks** [comment]
> Or maybe version the cached data?

Could be. You could ask in #pocoo what their reasoning behind this was :)
