### ISSUE TITLE
why decorated_function is used for timeout?

### ISSUE THREAD

**Issue by alexandnpu** [sh4nks/flask-caching#52]
https://github.com/sh4nks/flask-caching/blob/c929c4542d5d44bc0a6655f1195d90366a79b99a/flask_caching/__init__.py#L691

why decorated_function is used here?
Can you explain, please?

**Comment by sh4nks** [comment]
If you take a look here: https://github.com/sh4nks/flask-caching/blob/c929c4542d5d44bc0a6655f1195d90366a79b99a/flask_caching/__init__.py#L490 and here https://github.com/sh4nks/flask-caching/blob/c929c4542d5d44bc0a6655f1195d90366a79b99a/flask_caching/__init__.py#L495
you can see why. We get the value from the ``cache_timeout`` attribute from the ``decorated_function``

**Comment by alexandnpu** [comment]
Hmmm, So why not directly use `timeout= decorated_function.cache_timeout` on line 691?

That makes some confusion.
