### ISSUE TITLE
How to cache some data explicitly ?

### ISSUE THREAD

**Issue by kavink** [sh4nks/flask-caching#58]
After I read some big json file from somewhere, I want to make that internally available by my app to work on it, Or when user queries it to return from cache, I can use ```@cache.memoize()``` on get function for user to use and for my app to use, But there is a one time hit of getting the json from my DB. 

As I am populating that data myself, is it possible to populate that in cache explicitly so my app just uses that ?

**Comment by sh4nks** [comment]
Not sure if I understood you correctly, but you could use [these](https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L232-L260) functions to modify the cache 'directly'.

**Comment by robertlagrant** [comment]
@sh4nks I've the same question - it's not immediately clear how to access the cache directly from any place in the Flask application.
For example, the following doesn't work (not that it should; I'm just trying to figure out how to use it!):

```
    with app.app_context():
        app.cache.set("some_key", "some_value")
```
