### ISSUE TITLE
limit the cache size

### ISSUE THREAD

**Issue by eadmaster** [sh4nks/flask-caching#6]
is there a method to limit the cache size?
(eg. by entries or the size in bytes)

If i set `timeout=None` i may end up with a lot of entries in the cache after a while, so i need a way to limit them.

**Comment by sh4nks** [comment]
Hey,
no, this is not possible at the moment but I am happy to accept any pull requests! :)

**Comment by eadmaster** [comment]
As a workaround, i've found you can set an LRU eviction policy in the Redis instance.
Will flask-caching work correctly with that?

**Comment by jkreft-usgs** [comment]
Configuring a cache is something that should be done in the cache configuration, like you did. That's not a workaround, it is the right way to do it. Flask-catching will work fine with Redis LRU eviction policies set.
