### ISSUE TITLE
filesystem CACHE_TYPE not clear file with delete_memoized

### ISSUE THREAD

**Issue by JohnPortella** [sh4nks/flask-caching#62]
Hi,
I'm using flask app with uwgsi and ngnix. So, I configured `'CACHE_TYPE': 'filesystem', 'CACHE_DIR': tempfile.gettempdir()`. 

I have a job that update the cache somtimes. 

`cache.delete_memoized(f)`

It's working fine but the problem is when i check the temp directory, the past files still exist. 

```

14/03/2018  03:57 PM         5,452,969 1c90fe01368dd1f4a1e99707ac31e684
14/03/2018  03:57 PM        12,242,036 ba6d5eebaeb05afe29e3bde20f396fea
14/03/2018  03:57 PM        10,772,996 f611d864d2a4206fa6ac2d49e33cc2bd
14/03/2018  04:02 PM         5,493,106 c05247ee8087ffc1f43239a1afc3d0d9
14/03/2018  04:02 PM        12,286,872 35b28b3cd29a3afaf90ea86e66cd40e8
14/03/2018  04:03 PM        10,829,939 a4c14575c6412333e59cf0f700354943
14/03/2018  04:04 PM                22 00881cc24cbc428e8dfd137afb40ba2c
14/03/2018  04:05 PM         5,534,646 fd45b7456ce7cd62f7828d023b302083
14/03/2018  04:05 PM        12,339,879 8809360ecbe1ead558691cb13ccabfd8
14/03/2018  04:05 PM        10,858,896 f43b0ecfbb733c4c0af02e6f036b15af
14/03/2018  04:05 PM                 8 2029240f6d1128be89ddc32729463129
```
Is there any way to eliminate them with the library?. If not, is there a way to put a prefix to identify which files to delete?

**Comment by sh4nks** [comment]
To me this seems more like a problem on werkzeugs side as we are using the FileSystemCache from werkzeuzg: http://werkzeug.pocoo.org/docs/0.14/contrib/cache/#werkzeug.contrib.cache.FileSystemCache

**Comment by sh4nks** [comment]
You have to set the threshold to a lower number if you want flask-caching to delete the cache files.
See https://github.com/sh4nks/flask-caching/blob/master/flask_caching/backends/filesystem.py#L26

**Comment by sh4nks** [comment]
This is described here: https://flask-caching.readthedocs.io/en/latest/api.html#filesystemcache
