### ISSUE TITLE
delete_many stop at first error

### ISSUE THREAD

**Issue by johaven** [sh4nks/flask-caching#64]
```python
    def delete_many(self, *keys):
        """Deletes multiple keys at once.

        :param keys: The function accepts multiple keys as positional
                     arguments.
        :returns: Whether all given keys have been deleted.
        :rtype: boolean
        """
        return all(self.delete(key) for key in keys)
```
Currently the delete loop stops at the first item that is False (it's the behavior of the **all** function if evaluation is done inside)
This is annoying because you have to check the presence in the cache of all the keys you want to delete.
The default behaviour should be to continue the deletion despite the errors.
In this way the trick is to bypass the evaluation during the loop:
```python
 return all([self.delete(key) for key in keys])
```
Or add this as option ?
```python
def delete_many(self, *keys, ignore_errors=False)
```
Note: I found this problem with the file system cache

**Comment by sh4nks** [comment]
this is a problem with werkzeugs filesystem cache problem and not a flask-caching ones.

as you can see [here](https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L248), delete_many is just a proxy function to the underlying backend.

**Comment by johaven** [comment]
That's right I report on the werkzeug side

**Comment by sh4nks** [comment]
Looks like it's our problem now :P

**Comment by buckley-w-david** [comment]
@sh4nks I'll take a go at this issue, but before I do it's probably a good idea to discuss what the desired behavior is.

Right now the behavior of the delete_many method is actually inconsistent, in the cases where the cache just uses the inherited delete_many, the evaluation short circuits on a failure as this issue describes, but on classes that have overridden the method it'll be down to how it's implemented.

It's pretty simply to just change the delete_many method in the BaseCache to not short circuit, but the question is that this is actually a potentially breaking change, as it is possible that some user of the library is relying on this behavior.

That suggests that the addition of the `ignore_errors=False` flag to the method is a good one to resolve this, as it would allow the improved behavior without risking breaking existing implementations, but that has some strange implications on other cache objects (Like Memcached, that uses the underlying batch delete method to improve performance) of also having to honor the flag.

Do we consider the short circuit behavior a bug? It is unspecified behavior, so people really shouldn't have been relying on it. If we do consider it a bug, we wouldn't have to worry about the additional overhead of new deletion logic and impacting the performance of specialized delete methods.

**Comment by sh4nks** [comment]
@buckley-w-david sorry for my late response - I am very busy with uni stuff and have barely time to maintain my personal projects.. anyway, if you are still interested - go for it! :)

I like the idea of adding a ``ignore_errors=False`` flag but I don't understand why there would be any implications if it is by default ``False``?

I do, however, consider it a bug so we wouldn't have to worry about new deletion logic etc. I think this might even justify a major version pump to 2.0.

**Comment by sh4nks** [comment]
Hehe. Yeah, then lets do it this way :)

**Comment by johaven** [comment]
with a little delay, thank you :)
