### ISSUE TITLE
Support for sha256 in memoize key for FIPS compliance

### ISSUE THREAD

**Issue by eliasdawson** [sh4nks/flask-caching#65]
I am in the process of migrating my server to a FIPS-compliant OS which doesn't have md5 available which results in a segmentation fault when using the memoize decorator.

I'm wondering if it's possible to override the make_cache_key method or some other way to use sha256 instead of md5 to create the cache key with memoize.

https://github.com/sh4nks/flask-caching/blob/master/flask_caching/__init__.py#L513

Thanks!

**Comment by sh4nks** [comment]
Not that I know of but I'm happy to review a PR if you want to submit one.
