### ISSUE TITLE
datetime value for timeout parameter 

### ISSUE THREAD

**Issue by vitriol** [sh4nks/flask-caching#7]
Hey thanks for the fork. I'm looking into switching to this if it will continue to be maintained.

Any way we can include an option to pass a datetime for cache expiration as well? For example php's implementation of Memcached allows the option to send both a datetime and an int.

**Comment by sh4nks** [comment]
Hey,

as flask-caching is mostly just a wrapper around the caching module from werkzeug (http://werkzeug.pocoo.org/docs/0.11/contrib/cache/) is this unfortunately not possible.

**Comment by vitriol** [comment]
thx, I will try and raise the issue with them then
