### ISSUE TITLE
Caching based on POST body

### ISSUE THREAD

**Issue by rangerscience** [sh4nks/flask-caching#71]
I have requests that I want to cache that have array parameters (so they don't fit well in GET queries; have to stick stuff in the POST body). However, EITHER there's no way to get flask-caching to include the POST body as part of the cache key, OR, it's really not clear from the docs how to do this.

It seems like an "easy solution" would be for the decorator to accept a function argument for the `make_cache_key`.

**Comment by sh4nks** [comment]
I guess you are talking from the ``@cache.cached(timeout=50)`` decorator right?
If so, no we are not taking the POST body into account when creating the cache key.

I'm happy to review a PR if you want to submit one.
