### ISSUE TITLE
Deprecate werkzeug.contrib.cache

### ISSUE THREAD

**Issue by lepture** [sh4nks/flask-caching#72]
We are going to remove `werkzeug.contrib.cache` from werkzeug. Flask-Caching is depending on it, can you copy that part into your repo and maintain it in Flask-Caching.

https://github.com/pallets/werkzeug/issues/1249

**Comment by neilsh** [comment]
For reference, here's the code for `werkzeug.contrib.cache`: https://github.com/pallets/werkzeug/blob/master/werkzeug/contrib/cache.py

Flask-Caching relies on this module for the implementations of several of its caching backends:

https://github.com/sh4nks/flask-caching/blob/039d8aef5e3ebbb70c0f679f4e4452f80f594dd1/flask_caching/backends/backends.py#L11

**Comment by dchevell** [comment]
@lepture is this the sort of approach you're talking about: https://github.com/dchevell/flask-caching

I copied over the code from werkzeug.contrib.cache, replaced all imports in the core library and in tests, and updated the documentation to reference the internal implementations. Werkzeug origins are still clear.

All tests pass, and I tried the modded version in a project of mine that uses Flask-Caching and found no unexpected behaviours.

I'm not 100% confident in opening a PR without confirming whether this approach is the one you're looking for, or one that @sh4nks is happy with.

**Comment by lepture** [comment]
Yes, you can start with a copy of werkzeug.contrib.cache. But I do believe the cache module could be far more better than the one in werkzeug.

**Comment by sh4nks** [comment]
@dchevell that would be ok for now I think!


I actually had in mind to rewrite this extension to be a *simple* wrapper around dogpile.cache which would make maintaining this extension much easier. At the moment this is just an idea.. which lacks motivation and time :/

**Comment by sh4nks** [comment]
I am closing this now as we don't depend on werkzeug.contrib.cache anymore. Yay! :)
