### ISSUE TITLE
Share cache between applications

### ISSUE THREAD

**Issue by jinyus** [sh4nks/flask-caching#73]
I just realized that when trying to get an item set by another app would always return None, How can I share cache between apps using the same cache server? does the extension add a unique identifier to the key when setting an item in cache? If you, how would I get that get that identifier?

**Comment by alanhamlett** [comment]
Use the [Redis Cache Backend](https://flask-caching.readthedocs.io/en/latest/#rediscache) and configure all your app servers to use the same Redis host for Flask-Caching.

**Comment by sh4nks** [comment]
I think @alanhamlett answered your question.
