### ISSUE TITLE
Wrong example in docs

### ISSUE THREAD

**Issue by JungWinter** [sh4nks/flask-caching#79]
![image](https://user-images.githubusercontent.com/13811604/43062522-12508146-8e94-11e8-8323-8422882e7a0f.png)

I think It should be a below code.

```py
@cache.cached(timeout=50)
@app.route('/')
def index():
    return 'Cached for 50s'
```

**Comment by sh4nks** [comment]
I don't see whats wrong with them. Your posted example is wrong.

**Comment by alanhamlett** [comment]
Here's some more info about why `cached` should be the last decorator:
https://wakatime.com/blog/34-part-3-flask-api-decorators-and-helpers
