### ISSUE TITLE
[question] Multi-level caching

### ISSUE THREAD

**Issue by diogobaeder** [sh4nks/flask-caching#80]
Hi guys,

Sorry for opening a question issue here, but I couldn't find any user group for the library (I hope it's OK).

I'm starting to experiment with Flask-Caching for an application I'm building, and I'd like to know if the library supports multi-level caching. For example, can I have something like this?:

```
memory_cache = Cache(config=config_for_memory)
persistent_cache = Cache(config=config_for_persistent)
memory_cache.init_app(app)
persistent_cache.init_app(app)
```

Is the above expected to work? I need this because this application will have to deal with very fast access to in-memory cache but also a (not so very) fast persisted cache in certain cases.

Thanks!

Diogo

**Comment by sh4nks** [comment]
I don't see why this wouldn't work. Did you try it?
