### ISSUE TITLE
Publish API documentation

### ISSUE THREAD

**Issue by remeika** [sh4nks/flask-caching#83]
Flask-Caching has great prose-based documentation, but [does not publish API documentation](https://flask-caching.readthedocs.io/en/latest/#api). Adding this level of detail to the docs would help prevent issues like #58 and #82 from opened.

API docs should be auto generated and published as part of the release process.

**Comment by sh4nks** [comment]
Fixed with https://github.com/sh4nks/flask-caching/commit/6427db64b20e66b8916c20c63d7eaddf7433a87d.
