### ISSUE TITLE
Missing source distribution for v1.3.3?

### ISSUE THREAD

**Issue by mstone** [sh4nks/flask-caching#84]
Dear maintainer,

As discussed in https://github.com/garbas/pypi2nix/issues/220 and elsewhere, v1.3.3 of flask-caching was [released on PyPI](https://pypi.org/project/Flask-Caching/1.3.3/) without a corresponding source distribution and this is breaking attempts to install downstream projects like apache-airflow on systems that need to rebuild from source and that expect to be able to do so based on what's in PyPI.

As a result, will you please either

a) publish a corresponding source distribution for v1.3.3

or, if that is infeasible

b) republish the v1.3.3 code with both source and binary distributions as v1.3.4 so that downstream projects with version bounds like >=1.3.3,<1.4 pick up the new version?

Thank you!

**Comment by sh4nks** [comment]
Hey,

weird, seems like 1.3.3 is the only version where i forgot to upload the source distribution.
Anyway, I have published the sdist release for 1.3.3 but for some reason it's not showing up [here](https://pypi.org/project/Flask-Caching/1.3.3/#files)?

**Comment by mstone** [comment]
Beautiful, thank you!
