### ISSUE TITLE
Disable caching based on the response http status code

### ISSUE THREAD

**Issue by ronlut** [sh4nks/flask-caching#91]
Hi.
I'm looking for an option to disable caching for certain response status codes.
My flask endpoint queries another endpoint, and I return different status codes (in the 4XX-5XX range) depending on the problem I encountered with the second endpoint.
I want to disable caching for responses that are not within the "valid" range (2XX-3XX).
Is that somehow possible with flask-caching? The `unless` function is evaluated before my view function is invoked so I can't use the response.

Thanks

**Comment by sh4nks** [comment]
If this is not achievable with ``unless`` you have to implement your solution to disable caching for your specific issue. Sorry.
