### ISSUE TITLE
GAEMemcachedCache removed

### ISSUE THREAD

**Issue by patelnav** [sh4nks/flask-caching#95]
It looks like GAEMemcachedCache was removed and merged into memcached. This breaks folks who were using CACHE_TYPE = 'gaememcached'

Can this get documented explicitly, or maintain the mapping as previously done. This does break backwards compat for Google AppEngine Standard users

**Comment by sh4nks** [comment]
Ah yes, I shouldn't have removed the "CACHE_TYPE" mapping. I'll re-add the type "gaememcached" once I get to a computer.

**Comment by patelnav** [comment]
Awesome, thanks for the quick fix. Nitpick, but might be better to:
``` 
def gaememcached(*args, **kwargs):
    return memcached(*args, **kwargs)
```

**Comment by sh4nks** [comment]
Damnit, I knew it that there was a DRY way :see_no_evil:
